/** Triggers a real browser download of generated mock content — no server round trip. */
export function downloadTextFile(filename: string, content: string) {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" })
  const url = URL.createObjectURL(blob)
  const link = document.createElement("a")
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

function rule(char = "-", width = 46) {
  return char.repeat(width)
}

export function buildIssuedDocumentText(input: {
  title: string
  employeeName: string
  employeeId: string
  department: string
  designation: string
  issuedOn: string
}) {
  return `DAYFLOW
${rule("=")}
${input.title.toUpperCase()}
${rule()}

Issued to:     ${input.employeeName} (${input.employeeId})
Department:    ${input.department}
Designation:   ${input.designation}
Issued on:     ${input.issuedOn}

${rule()}
This is a mock ${input.title.toLowerCase()} generated by Dayflow for
demo purposes. In production this would be rendered from an
HR-approved template and issued as a signed PDF.
${rule()}

Dayflow HR — this document is not valid for official use.
`
}

export function buildPaySlipText(input: {
  employeeName: string
  employeeId: string
  month: string
  year: number
  lineItems: { label: string; amount: number }[]
  netPay: number
}) {
  const rows = input.lineItems
    .map((item) => {
      const amount = `${item.amount < 0 ? "-" : ""}₹${Math.abs(item.amount).toLocaleString("en-IN")}`
      return `  ${item.label.padEnd(28, " ")}${amount.padStart(14, " ")}`
    })
    .join("\n")

  return `DAYFLOW
${rule("=")}
SALARY SLIP — ${input.month.toUpperCase()} ${input.year}
${rule()}

Employee:      ${input.employeeName} (${input.employeeId})

${rows}
${rule()}
  ${"NET PAY".padEnd(28, " ")}${`₹${input.netPay.toLocaleString("en-IN")}`.padStart(14, " ")}
${rule("=")}

This is a mock pay slip generated by Dayflow for demo purposes.
`
}
