-- Dayflow Phase 5 (Communication): built-in HR email, an HR help desk, and a policy-grounded
-- employee self-service assistant. Email delivery goes through a provider interface with a local
-- development adapter (spec: "if an external email credential is unavailable, create a secure
-- provider interface and local adapter, clearly label the integration as pending") — no SMTP/
-- Gmail/Graph credentials are wired up, so sending here records a delivery rather than dispatching
-- a real message. The assistant is intent-routing over real HR data, not a generative-AI call —
-- there is no LLM credential configured in this backend either.

create table email_templates (
  id bigint generated by default as identity primary key,
  code varchar(60) not null unique,
  category varchar(40) not null,
  name varchar(140) not null,
  subject varchar(200) not null,
  body text not null,
  active boolean not null default true,
  created_by_user_id bigint references users(id),
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);

create table email_messages (
  id bigint generated by default as identity primary key,
  sender_user_id bigint not null references users(id),
  template_id bigint references email_templates(id),
  subject varchar(200) not null,
  body text not null,
  recipient_employee_ids text not null,
  recipient_count int not null default 0,
  status varchar(20) not null default 'DRAFT',
  scheduled_at timestamp,
  sent_at timestamp,
  bulk_confirmed boolean not null default false,
  failure_reason varchar(500),
  idempotency_key varchar(80) unique,
  created_at timestamp not null default current_timestamp
);
create index idx_email_messages_sender on email_messages(sender_user_id, status);

create table email_deliveries (
  id bigint generated by default as identity primary key,
  email_message_id bigint not null references email_messages(id),
  employee_id bigint not null references employees(id),
  email_address varchar(180) not null,
  status varchar(20) not null default 'QUEUED',
  sent_at timestamp,
  error_message varchar(500)
);
create index idx_email_deliveries_message on email_deliveries(email_message_id);

create table hr_tickets (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references employees(id),
  category varchar(40) not null,
  subject varchar(200) not null,
  description varchar(2000) not null,
  status varchar(20) not null default 'OPEN',
  priority varchar(20) not null default 'MEDIUM',
  confidential boolean not null default false,
  assigned_to_user_id bigint references users(id),
  sla_due_at timestamp not null,
  resolved_at timestamp,
  closed_at timestamp,
  satisfaction_rating int,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);
create index idx_hr_tickets_status on hr_tickets(status);
create index idx_hr_tickets_employee on hr_tickets(employee_id);

create table hr_ticket_messages (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references hr_tickets(id),
  author_user_id bigint references users(id),
  body varchar(2000) not null,
  internal_note boolean not null default false,
  created_at timestamp not null default current_timestamp
);
create index idx_hr_ticket_messages_ticket on hr_ticket_messages(ticket_id);

create table policies (
  id bigint generated by default as identity primary key,
  code varchar(60) not null unique,
  title varchar(200) not null,
  category varchar(60) not null,
  body text not null,
  effective_date date not null,
  active boolean not null default true,
  created_at timestamp not null default current_timestamp
);

create table assistant_interactions (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references employees(id),
  question varchar(500) not null,
  intent varchar(60) not null,
  answer varchar(2000) not null,
  policy_id bigint references policies(id),
  action_taken varchar(100),
  created_at timestamp not null default current_timestamp
);
create index idx_assistant_interactions_employee on assistant_interactions(employee_id);
