-- Auth security extensions for passkeys, recovery, activation and device/session visibility.
-- WebAuthn stores public credential material only. Raw biometric data is never collected or stored.

alter table refresh_tokens add column if not exists user_agent varchar(300);
alter table refresh_tokens add column if not exists device_name varchar(120);
alter table refresh_tokens add column if not exists last_used_at timestamp;

create table webauthn_credentials (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id),
  credential_id varchar(500) not null unique,
  public_key text not null,
  sign_count bigint not null default 0,
  device_name varchar(120) not null,
  transports varchar(200),
  created_at timestamp not null default current_timestamp,
  last_used_at timestamp
);

create table auth_challenges (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id),
  challenge_hash varchar(128) not null unique,
  purpose varchar(40) not null,
  expires_at timestamp not null,
  used_at timestamp,
  created_at timestamp not null default current_timestamp
);

create table email_verification_tokens (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id),
  identifier varchar(180) not null,
  token_hash varchar(128) not null unique,
  purpose varchar(40) not null,
  expires_at timestamp not null,
  used_at timestamp,
  created_at timestamp not null default current_timestamp
);

create table password_reset_tokens (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id),
  token_hash varchar(128) not null unique,
  expires_at timestamp not null,
  used_at timestamp,
  created_at timestamp not null default current_timestamp
);

create table login_attempts (
  id bigint generated by default as identity primary key,
  identifier varchar(180) not null,
  success boolean not null,
  ip_address varchar(80),
  created_at timestamp not null default current_timestamp
);

create table security_events (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id),
  event_type varchar(80) not null,
  severity varchar(20) not null,
  detail varchar(500) not null,
  ip_address varchar(80),
  created_at timestamp not null default current_timestamp
);

create table recovery_codes (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id),
  code_hash varchar(128) not null unique,
  used_at timestamp,
  created_at timestamp not null default current_timestamp
);

create index idx_webauthn_credentials_user on webauthn_credentials(user_id);
create index idx_auth_challenges_purpose on auth_challenges(purpose, expires_at);
create index idx_email_verification_identifier on email_verification_tokens(identifier, purpose);
create index idx_password_reset_user on password_reset_tokens(user_id);
create index idx_login_attempts_identifier on login_attempts(identifier, created_at);
create index idx_security_events_user on security_events(user_id, created_at);
