-- Phase 6 (Intelligence): performance goals/reviews. Workforce insights (headcount trend,
-- attrition risk) are computed on the fly from existing employee/attendance/leave data and
-- don't need their own tables.

create table goals (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references employees(id),
  title varchar(200) not null,
  description varchar(2000),
  category varchar(60) not null default 'Individual',
  due_date date,
  status varchar(20) not null default 'IN_PROGRESS',
  progress_percent integer not null default 0,
  created_by_user_id bigint not null references users(id),
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);
create index idx_goals_employee on goals(employee_id);

create table performance_reviews (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references employees(id),
  reviewer_user_id bigint not null references users(id),
  cycle varchar(40) not null,
  rating integer,
  strengths varchar(2000),
  improvements varchar(2000),
  manager_comments varchar(2000),
  status varchar(20) not null default 'DRAFT',
  submitted_at timestamp,
  acknowledged_at timestamp,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);
create index idx_reviews_employee on performance_reviews(employee_id);
