create table if not exists roles (
  id bigint generated by default as identity primary key,
  name varchar(80) not null unique
);

create table if not exists permissions (
  id bigint generated by default as identity primary key,
  code varchar(120) not null unique
);

create table if not exists role_permissions (
  role_id bigint not null references roles(id),
  permission_id bigint not null references permissions(id),
  primary key (role_id, permission_id)
);

create table if not exists users (
  id bigint generated by default as identity primary key,
  name varchar(140) not null,
  email varchar(180) not null unique,
  password_hash varchar(200) not null,
  role_id bigint not null references roles(id),
  active boolean not null default true,
  created_at timestamp not null default current_timestamp
);

create table if not exists departments (
  id bigint generated by default as identity primary key,
  name varchar(120) not null unique,
  location varchar(120) not null
);

create table if not exists positions (
  id bigint generated by default as identity primary key,
  title varchar(120) not null unique
);

create table if not exists employees (
  id bigint generated by default as identity primary key,
  employee_code varchar(40) not null unique,
  user_id bigint references users(id),
  name varchar(140) not null,
  email varchar(180) not null unique,
  department_id bigint references departments(id),
  position_id bigint references positions(id),
  manager_id bigint references employees(id),
  location varchar(120) not null,
  employment_type varchar(60) not null,
  status varchar(40) not null,
  joining_date date not null,
  salary decimal(14,2) not null default 0,
  bank_verified boolean not null default false
);

create table if not exists attendance (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references employees(id),
  work_date date not null,
  check_in timestamp,
  check_out timestamp,
  status varchar(40) not null,
  late_minutes int not null default 0,
  overtime_minutes int not null default 0,
  unique(employee_id, work_date)
);

create table if not exists leave_requests (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references employees(id),
  leave_type varchar(80) not null,
  start_date date not null,
  end_date date not null,
  working_days decimal(6,2) not null,
  status varchar(40) not null,
  reason varchar(500) not null,
  rejection_reason varchar(500),
  created_at timestamp not null default current_timestamp
);

create table if not exists leave_balances (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references employees(id),
  leave_type varchar(80) not null,
  balance decimal(7,2) not null,
  unique(employee_id, leave_type)
);

create table if not exists payroll_runs (
  id bigint generated by default as identity primary key,
  payroll_month varchar(7) not null,
  status varchar(40) not null,
  gross_total decimal(14,2) not null,
  exception_count int not null default 0,
  created_at timestamp not null default current_timestamp
);

create table if not exists payroll_anomalies (
  id bigint generated by default as identity primary key,
  payroll_run_id bigint not null references payroll_runs(id),
  employee_id bigint not null references employees(id),
  issue varchar(160) not null,
  severity varchar(20) not null,
  possible_cause varchar(260) not null,
  recommended_action varchar(260) not null,
  review_status varchar(40) not null
);

create table if not exists email_templates (
  id bigint generated by default as identity primary key,
  name varchar(120) not null,
  subject varchar(180) not null,
  body clob not null
);

create table if not exists email_messages (
  id bigint generated by default as identity primary key,
  sender_user_id bigint not null references users(id),
  subject varchar(180) not null,
  body clob not null,
  recipients clob not null,
  status varchar(40) not null,
  scheduled_at timestamp,
  created_at timestamp not null default current_timestamp
);

create table if not exists hr_tickets (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references employees(id),
  category varchar(80) not null,
  subject varchar(180) not null,
  status varchar(60) not null,
  priority varchar(20) not null,
  confidential boolean not null default false,
  sla_due_at timestamp not null,
  assigned_to bigint references users(id),
  created_at timestamp not null default current_timestamp
);

create table if not exists automation_rules (
  id bigint generated by default as identity primary key,
  name varchar(140) not null,
  description varchar(500) not null,
  owner_user_id bigint not null references users(id),
  trigger_name varchar(120) not null,
  condition_text varchar(500) not null,
  action_text varchar(500) not null,
  active boolean not null,
  test_mode boolean not null,
  high_risk boolean not null,
  last_run_at timestamp,
  success_rate decimal(5,2) not null default 0
);

create table if not exists notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id),
  title varchar(180) not null,
  body varchar(500) not null,
  severity varchar(20) not null,
  read_at timestamp,
  created_at timestamp not null default current_timestamp
);

create table if not exists audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id bigint references users(id),
  action varchar(120) not null,
  entity varchar(120) not null,
  entity_id varchar(80),
  previous_value clob,
  new_value clob,
  reason varchar(500),
  request_id varchar(80) not null,
  ip_address varchar(80),
  created_at timestamp not null default current_timestamp
);
