-- Dayflow Phase 1 (Foundation): auth, permissions, employee directory, audit.
-- Later phases (attendance, leave, payroll, email, tickets, automation, ...) add their own tables.

create table roles (
  id bigint generated by default as identity primary key,
  name varchar(60) not null unique,
  description varchar(200) not null
);

create table permissions (
  id bigint generated by default as identity primary key,
  code varchar(80) not null unique,
  description varchar(200) not null
);

create table role_permissions (
  role_id bigint not null references roles(id),
  permission_id bigint not null references permissions(id),
  primary key (role_id, permission_id)
);

create table departments (
  id bigint generated by default as identity primary key,
  name varchar(120) not null unique,
  location varchar(120) not null
);

create table employees (
  id bigint generated by default as identity primary key,
  employee_code varchar(20) unique,
  name varchar(140) not null,
  email varchar(180) not null unique,
  phone varchar(40),
  department_id bigint references departments(id),
  designation varchar(140),
  manager_id bigint references employees(id),
  location varchar(120),
  employment_type varchar(40),
  status varchar(40) not null default 'Onboarding',
  joining_date date,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);

create table users (
  id bigint generated by default as identity primary key,
  employee_id bigint not null unique references employees(id),
  email varchar(180) not null unique,
  password_hash varchar(200) not null,
  role_id bigint not null references roles(id),
  active boolean not null default true,
  created_at timestamp not null default current_timestamp,
  last_login_at timestamp
);

create table refresh_tokens (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id),
  token_hash varchar(128) not null unique,
  expires_at timestamp not null,
  revoked_at timestamp,
  replaced_by_hash varchar(128),
  created_at timestamp not null default current_timestamp,
  created_ip varchar(80)
);

create table invitations (
  id bigint generated by default as identity primary key,
  email varchar(180) not null,
  role_id bigint not null references roles(id),
  employee_id bigint references employees(id),
  token_hash varchar(128) not null unique,
  status varchar(20) not null default 'PENDING',
  invited_by_user_id bigint references users(id),
  expires_at timestamp not null,
  accepted_at timestamp,
  revoked_at timestamp,
  created_at timestamp not null default current_timestamp
);

create table employee_job_history (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references employees(id),
  department_id bigint references departments(id),
  designation varchar(140),
  manager_id bigint references employees(id),
  employment_type varchar(40),
  status varchar(40) not null,
  effective_date date not null,
  change_type varchar(40) not null,
  reason varchar(500),
  changed_by_user_id bigint references users(id),
  created_at timestamp not null default current_timestamp
);

create table audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id bigint references users(id),
  action varchar(120) not null,
  entity varchar(120) not null,
  entity_id varchar(80),
  previous_value text,
  new_value text,
  reason varchar(500),
  request_id varchar(80) not null,
  ip_address varchar(80),
  created_at timestamp not null default current_timestamp
);

create index idx_employees_department on employees(department_id);
create index idx_employees_manager on employees(manager_id);
create index idx_employees_status on employees(status);
create index idx_job_history_employee on employee_job_history(employee_id);
create index idx_audit_logs_entity on audit_logs(entity, entity_id);
create index idx_audit_logs_created_at on audit_logs(created_at);
create index idx_invitations_status on invitations(status);
create index idx_refresh_tokens_user on refresh_tokens(user_id);
