-- Dayflow Phase 2 (Core HR): attendance, shifts, leave, holidays, in-app notifications.

create table shifts (
  id bigint generated by default as identity primary key,
  name varchar(80) not null unique,
  start_time time not null,
  end_time time not null,
  grace_minutes int not null default 0,
  break_minutes int not null default 0,
  created_at timestamp not null default current_timestamp
);

alter table employees add column shift_id bigint references shifts(id);

create table holidays (
  id bigint generated by default as identity primary key,
  holiday_date date not null,
  name varchar(140) not null,
  location varchar(120),
  created_at timestamp not null default current_timestamp
);
create index idx_holidays_date on holidays(holiday_date);

create table attendance_records (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references employees(id),
  work_date date not null,
  check_in timestamp,
  check_out timestamp,
  status varchar(20) not null,
  late_minutes int not null default 0,
  early_departure_minutes int not null default 0,
  overtime_minutes int not null default 0,
  missing_checkout_notified boolean not null default false,
  source varchar(20) not null default 'PORTAL',
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  unique (employee_id, work_date)
);
create index idx_attendance_employee_date on attendance_records(employee_id, work_date);
create index idx_attendance_missing_checkout on attendance_records(work_date, check_out, missing_checkout_notified);

create table attendance_corrections (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references employees(id),
  work_date date not null,
  requested_check_in timestamp,
  requested_check_out timestamp,
  reason varchar(500) not null,
  evidence_note varchar(500),
  status varchar(20) not null default 'PENDING',
  decided_by_user_id bigint references users(id),
  decision_reason varchar(500),
  created_at timestamp not null default current_timestamp,
  decided_at timestamp
);
create index idx_attendance_corrections_employee on attendance_corrections(employee_id);
create index idx_attendance_corrections_status on attendance_corrections(status);

create table leave_types (
  id bigint generated by default as identity primary key,
  name varchar(80) not null unique,
  description varchar(300) not null,
  requires_approval boolean not null default true,
  max_consecutive_days int,
  paid boolean not null default true,
  active boolean not null default true
);

create table leave_balances (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references employees(id),
  leave_type_id bigint not null references leave_types(id),
  balance decimal(6,2) not null default 0,
  updated_at timestamp not null default current_timestamp,
  unique (employee_id, leave_type_id)
);

create table leave_requests (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references employees(id),
  leave_type_id bigint not null references leave_types(id),
  start_date date not null,
  end_date date not null,
  days decimal(5,2) not null,
  reason varchar(500) not null,
  status varchar(20) not null default 'PENDING',
  approver_user_id bigint references users(id),
  decision_reason varchar(500),
  auto_approved boolean not null default false,
  created_at timestamp not null default current_timestamp,
  decided_at timestamp,
  cancelled_at timestamp
);
create index idx_leave_requests_employee on leave_requests(employee_id);
create index idx_leave_requests_status on leave_requests(status);
create index idx_leave_requests_dates on leave_requests(start_date, end_date);

create table notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id),
  category varchar(40) not null,
  severity varchar(20) not null default 'INFO',
  title varchar(180) not null,
  body varchar(500) not null,
  link varchar(200),
  read_at timestamp,
  created_at timestamp not null default current_timestamp
);
create index idx_notifications_user on notifications(user_id, read_at);
