-- Dayflow Team Management (spec §41): teams, projects, tasks and workload/capacity.

insert into permissions (code, description) values
  ('team:read', 'Read teams, members and team workspaces'),
  ('team:write', 'Create teams and manage memberships'),
  ('project:read', 'Read projects and milestones'),
  ('project:write', 'Create and update projects'),
  ('task:read', 'Read tasks and work queues'),
  ('task:write', 'Create, assign and update tasks'),
  ('workload:read', 'Read workload and capacity signals');

insert into role_permissions (role_id, permission_id)
  select r.id, p.id from roles r join permissions p
    on p.code in ('team:read','team:write','project:read','project:write','task:read','task:write','workload:read')
  where r.name = 'SUPER_ADMIN';

insert into role_permissions (role_id, permission_id)
  select r.id, p.id from roles r join permissions p
    on p.code in ('team:read','team:write','project:read','project:write','task:read','task:write','workload:read')
  where r.name in ('HR_ADMIN','HR_OFFICER');

insert into role_permissions (role_id, permission_id)
  select r.id, p.id from roles r join permissions p
    on p.code in ('team:read','team:write','project:read','project:write','task:read','task:write','workload:read')
  where r.name = 'MANAGER';

insert into role_permissions (role_id, permission_id)
  select r.id, p.id from roles r join permissions p
    on p.code in ('team:read','project:read','task:read','workload:read')
  where r.name in ('EMPLOYEE','AUDITOR');

create table teams (
  id bigint generated by default as identity primary key,
  name varchar(140) not null,
  code varchar(30) not null unique,
  type varchar(60) not null,
  description varchar(500),
  objective varchar(500),
  department_id bigint references departments(id),
  location varchar(120),
  cost_center varchar(80),
  owner_employee_id bigint references employees(id),
  lead_employee_id bigint references employees(id),
  deputy_lead_employee_id bigint references employees(id),
  start_date date,
  end_date date,
  working_days varchar(80) not null default 'MON,TUE,WED,THU,FRI',
  time_zone varchar(80) not null default 'Asia/Kolkata',
  default_shift_id bigint references shifts(id),
  visibility varchar(40) not null default 'Internal',
  capacity_hours_per_week decimal(7,2) not null default 40.00,
  notification_settings varchar(500),
  active boolean not null default true,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);

create table team_memberships (
  id bigint generated by default as identity primary key,
  team_id bigint not null references teams(id),
  employee_id bigint not null references employees(id),
  team_role varchar(60) not null,
  allocation_percent decimal(5,2) not null default 100.00,
  effective_from date not null default current_date,
  effective_to date,
  temporary_cover_employee_id bigint references employees(id),
  delegation_note varchar(500),
  active boolean not null default true,
  created_at timestamp not null default current_timestamp,
  unique(team_id, employee_id, effective_from)
);

create table projects (
  id bigint generated by default as identity primary key,
  name varchar(160) not null,
  code varchar(30) not null unique,
  description varchar(1000),
  business_outcome varchar(700),
  sponsor_employee_id bigint not null references employees(id),
  owner_employee_id bigint not null references employees(id),
  start_date date,
  target_date date,
  priority varchar(30) not null default 'Medium',
  status varchar(40) not null default 'Planning',
  budget_amount decimal(12,2),
  completion_percent decimal(5,2) not null default 0.00,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);

create table project_teams (
  project_id bigint not null references projects(id),
  team_id bigint not null references teams(id),
  primary key(project_id, team_id)
);

create table project_milestones (
  id bigint generated by default as identity primary key,
  project_id bigint not null references projects(id),
  name varchar(160) not null,
  status varchar(40) not null default 'Not Started',
  due_date date,
  completion_percent decimal(5,2) not null default 0.00,
  created_at timestamp not null default current_timestamp
);

create table tasks (
  id bigint generated by default as identity primary key,
  project_id bigint not null references projects(id),
  team_id bigint references teams(id),
  title varchar(180) not null,
  description varchar(1000),
  type varchar(40) not null default 'Task',
  status varchar(40) not null default 'To Do',
  priority varchar(30) not null default 'Medium',
  reporter_employee_id bigint references employees(id),
  reviewer_employee_id bigint references employees(id),
  due_date date,
  estimated_hours decimal(7,2) not null default 0,
  actual_hours decimal(7,2) not null default 0,
  automation_hint varchar(700),
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);

create table task_assignees (
  id bigint generated by default as identity primary key,
  task_id bigint not null references tasks(id),
  employee_id bigint not null references employees(id),
  role varchar(60) not null default 'Owner',
  allocation_percent decimal(5,2) not null default 100.00,
  assigned_at timestamp not null default current_timestamp,
  unique(task_id, employee_id)
);

create table task_comments (
  id bigint generated by default as identity primary key,
  task_id bigint not null references tasks(id),
  author_user_id bigint references users(id),
  body varchar(1000) not null,
  created_at timestamp not null default current_timestamp
);

create index idx_team_memberships_team on team_memberships(team_id);
create index idx_team_memberships_employee on team_memberships(employee_id);
create index idx_projects_status on projects(status);
create index idx_project_teams_team on project_teams(team_id);
create index idx_tasks_status on tasks(status);
create index idx_tasks_team on tasks(team_id);
create index idx_tasks_project on tasks(project_id);
create index idx_task_assignees_employee on task_assignees(employee_id);

insert into teams(name, code, type, description, objective, department_id, location, cost_center,
  owner_employee_id, lead_employee_id, start_date, capacity_hours_per_week, notification_settings)
select 'Engineering Delivery', 'TEAM-ENG-DEL', 'Department', 'Core product delivery group',
  'Deliver secure HR workflows and automation', d.id, 'Hyderabad', 'ENG-100', e1.id, e2.id,
  date '2026-04-24', 120.00, 'Notify lead for overdue tasks and member overload'
from departments d
join employees e1 on e1.email = 'admin@dayflow.test'
join employees e2 on e2.email = 'manager@dayflow.test'
where d.name = 'Engineering';

insert into teams(name, code, type, description, objective, department_id, location, cost_center,
  owner_employee_id, lead_employee_id, start_date, capacity_hours_per_week, notification_settings)
select 'People Operations Squad', 'TEAM-POP-OPS', 'Cross-functional', 'HR operations and employee experience group',
  'Reduce repetitive HR administration and improve employee service', d.id, 'Bengaluru', 'POP-200',
  e1.id, e1.id, date '2026-05-24', 80.00, 'Notify HR for onboarding, leave and document risks'
from departments d
join employees e1 on e1.email = 'admin@dayflow.test'
where d.name = 'People Operations';

insert into team_memberships(team_id, employee_id, team_role, allocation_percent, effective_from)
select t.id, e.id, 'Owner', 35.00, date '2026-05-24'
from teams t join employees e on e.email = 'admin@dayflow.test'
where t.code = 'TEAM-POP-OPS';

insert into team_memberships(team_id, employee_id, team_role, allocation_percent, effective_from)
select t.id, e.id, 'Lead', 80.00, date '2026-04-24'
from teams t join employees e on e.email = 'manager@dayflow.test'
where t.code = 'TEAM-ENG-DEL';

insert into team_memberships(team_id, employee_id, team_role, allocation_percent, effective_from)
select t.id, e.id, 'Member', 70.00, date '2026-06-03'
from teams t join employees e on e.email = 'employee@dayflow.test'
where t.code = 'TEAM-ENG-DEL';

insert into projects(name, code, description, business_outcome, sponsor_employee_id, owner_employee_id,
  start_date, target_date, priority, status, budget_amount, completion_percent)
select 'Dayflow Automation Launch', 'PRJ-AUTO-01', 'Launch transparent automation for reminders, approvals and reports',
  'Automation success rate above 95%', admin.id, manager.id, date '2026-07-23', date '2026-10-06',
  'High', 'In Progress', 360000.00, 42.00
from employees admin join employees manager on manager.email = 'manager@dayflow.test'
where admin.email = 'admin@dayflow.test';

insert into project_teams(project_id, team_id)
select p.id, t.id from projects p join teams t on t.code = 'TEAM-ENG-DEL'
where p.code = 'PRJ-AUTO-01';

insert into project_milestones(project_id, name, due_date, status, completion_percent)
select id, 'Automation rule builder MVP', date '2026-09-05', 'In Progress', 60.00
from projects where code = 'PRJ-AUTO-01';

insert into project_milestones(project_id, name, due_date, status, completion_percent)
select id, 'Payroll exception guardrails', date '2026-09-19', 'Not Started', 0.00
from projects where code = 'PRJ-AUTO-01';

insert into tasks(project_id, team_id, title, description, status, priority, reporter_employee_id, reviewer_employee_id,
  due_date, estimated_hours, automation_hint)
select p.id, t.id, 'Design team workload dashboard', 'Show available capacity, overload risks and leave impact.',
  'In Progress', 'High', manager.id, admin.id, date '2026-08-29', 24.00, 'Auto-surface overloaded members before assignment'
from projects p join teams t on t.code = 'TEAM-ENG-DEL'
join employees admin on admin.email = 'admin@dayflow.test'
join employees manager on manager.email = 'manager@dayflow.test'
where p.code = 'PRJ-AUTO-01';

insert into tasks(project_id, team_id, title, description, status, priority, reporter_employee_id, reviewer_employee_id,
  due_date, estimated_hours, automation_hint)
select p.id, t.id, 'Draft HR bulk email approval preview', 'Confirm recipients, exclusions and sensitive fields before sending.',
  'To Do', 'Medium', admin.id, admin.id, date '2026-09-01', 16.00, 'Require human approval before broad communication'
from projects p join teams t on t.code = 'TEAM-POP-OPS'
join employees admin on admin.email = 'admin@dayflow.test'
where p.code = 'PRJ-AUTO-01';

insert into task_assignees(task_id, employee_id, allocation_percent)
select task.id, e.id, 60.00
from tasks task join employees e on e.email = 'employee@dayflow.test'
where task.title = 'Design team workload dashboard';

insert into task_assignees(task_id, employee_id, allocation_percent)
select task.id, e.id, 40.00
from tasks task join employees e on e.email = 'admin@dayflow.test'
where task.title = 'Draft HR bulk email approval preview';
