-- Dayflow Phase 3 (Automation): a small, safe rule engine for reminders/escalations only.
-- Core transactional side effects (balance deduction, attendance sync on leave approval, etc.)
-- stay hardcoded in their services — this engine only ever sends reminders/notifications, so a
-- rule being toggled off or misconfigured can never silently break business state.

create table automation_rules (
  id bigint generated by default as identity primary key,
  code varchar(60) not null unique,
  name varchar(140) not null,
  description varchar(500) not null,
  trigger_type varchar(40) not null,
  config text not null,
  active boolean not null default true,
  test_mode boolean not null default false,
  high_risk boolean not null default false,
  owner_user_id bigint references users(id),
  last_run_at timestamp,
  last_run_status varchar(20),
  run_count int not null default 0,
  success_count int not null default 0,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);

create table automation_executions (
  id bigint generated by default as identity primary key,
  rule_id bigint not null references automation_rules(id),
  started_at timestamp not null,
  finished_at timestamp,
  status varchar(20) not null,
  matched_count int not null default 0,
  action_count int not null default 0,
  detail varchar(500),
  error_message varchar(500)
);
create index idx_automation_executions_rule on automation_executions(rule_id, started_at desc);

-- Idempotency markers so the leave-pending-reminder rule sends each nudge exactly once.
alter table leave_requests add column reminder_sent_at timestamp;
alter table leave_requests add column escalated_at timestamp;
