-- Dayflow Phase 4 (Payroll): versioned salary structures, a Draft->Paid payroll cycle with
-- maker-checker approval, and an anomaly engine that blocks publication on real risk signals.

alter table employees add column bank_verified boolean not null default false;
alter table employees add column tax_id_verified boolean not null default false;

create table salary_structures (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references employees(id),
  effective_from date not null,
  effective_to date,
  basic_monthly decimal(12,2) not null,
  hra_monthly decimal(12,2) not null default 0,
  allowances_monthly decimal(12,2) not null default 0,
  recurring_deductions_monthly decimal(12,2) not null default 0,
  status varchar(20) not null default 'ACTIVE',
  reason varchar(500),
  created_by_user_id bigint references users(id),
  created_at timestamp not null default current_timestamp
);
create index idx_salary_structures_employee on salary_structures(employee_id, status);

create table payroll_runs (
  id bigint generated by default as identity primary key,
  period_month varchar(7) not null unique,
  status varchar(20) not null default 'DRAFT',
  calculated_by_user_id bigint references users(id),
  calculated_at timestamp,
  approved_by_user_id bigint references users(id),
  approved_at timestamp,
  approval_reason varchar(500),
  published_by_user_id bigint references users(id),
  published_at timestamp,
  paid_at timestamp,
  total_gross decimal(14,2) not null default 0,
  total_deductions decimal(14,2) not null default 0,
  total_net decimal(14,2) not null default 0,
  employee_count int not null default 0,
  created_by_user_id bigint references users(id),
  created_at timestamp not null default current_timestamp
);

create table payroll_lines (
  id bigint generated by default as identity primary key,
  payroll_run_id bigint not null references payroll_runs(id),
  employee_id bigint not null references employees(id),
  salary_structure_id bigint references salary_structures(id),
  basic decimal(12,2) not null default 0,
  hra decimal(12,2) not null default 0,
  allowances decimal(12,2) not null default 0,
  overtime_pay decimal(12,2) not null default 0,
  gross_earnings decimal(12,2) not null default 0,
  unpaid_leave_days decimal(5,2) not null default 0,
  unpaid_leave_deduction decimal(12,2) not null default 0,
  tax_deduction decimal(12,2) not null default 0,
  other_deductions decimal(12,2) not null default 0,
  total_deductions decimal(12,2) not null default 0,
  net_pay decimal(12,2) not null default 0,
  created_at timestamp not null default current_timestamp,
  unique (payroll_run_id, employee_id)
);
create index idx_payroll_lines_employee on payroll_lines(employee_id);

create table payroll_anomalies (
  id bigint generated by default as identity primary key,
  payroll_run_id bigint not null references payroll_runs(id),
  employee_id bigint references employees(id),
  issue_code varchar(60) not null,
  severity varchar(20) not null,
  possible_cause varchar(300) not null,
  recommended_action varchar(300) not null,
  blocking boolean not null default false,
  review_status varchar(20) not null default 'OPEN',
  resolution_note varchar(500),
  reviewed_by_user_id bigint references users(id),
  reviewed_at timestamp,
  created_at timestamp not null default current_timestamp
);
create index idx_payroll_anomalies_run on payroll_anomalies(payroll_run_id, review_status);
