import { useState } from "react"
import { Link, useNavigate, useSearchParams } from "react-router-dom"
import { api } from "../lib/api"
import { useAuth } from "../lib/auth"

function Frame({ title, subtitle, children }: { title:string; subtitle:string; children:React.ReactNode }) { return <main className="auth-flow"><Link className="auth-flow-logo" to="/sign-in"><span>D</span>Dayflow</Link><section><h1>{title}</h1><p>{subtitle}</p>{children}</section></main> }
function ErrorText({ value }:{value:string}){return value?<p className="auth-error" role="alert">{value}</p>:null}

export function ForgotPasswordPage(){const [identifier,setIdentifier]=useState("");const [sent,setSent]=useState(false);const [error,setError]=useState("");async function submit(e:React.FormEvent){e.preventDefault();setError("");try{await api("/api/auth/password/forgot",{method:"POST",body:JSON.stringify({identifier})},false);setSent(true)}catch(err){setError(err instanceof Error?err.message:"Recovery could not start.")}}return <Frame title="Recover your account" subtitle="Use your company email or Employee ID. The confirmation is the same for every account.">{sent?<div className="auth-flow-result"><h2>Check your inbox</h2><p>If the account can be verified, recovery instructions will be sent.</p><Link to="/sign-in">Return to sign in</Link></div>:<form onSubmit={submit}><label>Company email or Employee ID<input required value={identifier} onChange={e=>setIdentifier(e.target.value)}/></label><ErrorText value={error}/><button>Send recovery instructions</button></form>}</Frame>}

export function ResetPasswordPage(){const [params]=useSearchParams();const navigate=useNavigate();const [password,setPassword]=useState("");const [confirm,setConfirm]=useState("");const [error,setError]=useState("");async function submit(e:React.FormEvent){e.preventDefault();if(password!==confirm){setError("Passwords do not match.");return}try{await api("/api/auth/password/reset",{method:"POST",body:JSON.stringify({token:params.get("token"),password})},false);navigate("/sign-in?passwordReset=1")}catch(err){setError(err instanceof Error?err.message:"Password could not be reset.")}}return <Frame title="Create a new password" subtitle="This signs out your other Dayflow sessions."><form onSubmit={submit}><label>New password<input type="password" minLength={12} required value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Confirm password<input type="password" minLength={12} required value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><p className="auth-flow-hint">Use at least 12 characters with uppercase, lowercase, and a number.</p><ErrorText value={error}/><button>Reset password</button></form></Frame>}

export function OtpPage(){const [params]=useSearchParams();const {verifyAdminOtp}=useAuth();const navigate=useNavigate();const identifier=params.get("identifier")??"";const purpose=params.get("purpose")??"ADMIN_LOGIN";const [code,setCode]=useState("");const [error,setError]=useState("");async function submit(e:React.FormEvent){e.preventDefault();try{if(purpose==="ADMIN_LOGIN"){await verifyAdminOtp(identifier,code);navigate("/admin/dashboard")}else await api("/api/auth/email/verify-otp",{method:"POST",body:JSON.stringify({identifier,purpose,code})},false)}catch(err){setError(err instanceof Error?err.message:"The verification code is invalid or expired.")}}return <Frame title="Verify it’s you" subtitle="Enter the six-digit code sent to your company email."><form onSubmit={submit}><label>Verification code<input inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,""))}/></label><ErrorText value={error}/><button>Verify and continue</button></form></Frame>}

export function ActivateEmployeePage(){const [step,setStep]=useState(1);const [form,setForm]=useState({employeeId:"",companyEmail:"",code:"",password:"",confirm:"",accepted:false});const [error,setError]=useState("");async function start(e:React.FormEvent){e.preventDefault();try{await api("/api/auth/employee/activate",{method:"POST",body:JSON.stringify(form)},false);setStep(2)}catch(err){setError(err instanceof Error?err.message:"Activation could not start.")}}async function finish(e:React.FormEvent){e.preventDefault();if(form.password!==form.confirm){setError("Passwords do not match.");return}try{await api("/api/auth/employee/activate/complete",{method:"POST",body:JSON.stringify(form)},false);setStep(3)}catch(err){setError(err instanceof Error?err.message:"Activation could not be completed.")}}return <Frame title="Activate employee account" subtitle={`Step ${step} of 3 · Your role comes from your employee record.`}>{step===1?<form onSubmit={start}><label>Employee ID<input required value={form.employeeId} onChange={e=>setForm({...form,employeeId:e.target.value})}/></label><label>Company email<input type="email" required value={form.companyEmail} onChange={e=>setForm({...form,companyEmail:e.target.value})}/></label><ErrorText value={error}/><button>Verify employee record</button></form>:step===2?<form onSubmit={finish}><label>Email verification code<input required pattern="[0-9]{6}" value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/></label><label>Create password<input type="password" required minLength={12} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><label>Confirm password<input type="password" required minLength={12} value={form.confirm} onChange={e=>setForm({...form,confirm:e.target.value})}/></label><label className="auth-check"><input type="checkbox" required checked={form.accepted} onChange={e=>setForm({...form,accepted:e.target.checked})}/>I accept the privacy and acceptable-use policies.</label><ErrorText value={error}/><button>Activate employee account</button></form>:<div className="auth-flow-result"><h2>Account activated</h2><p>Your employee account is ready. You can set up a passkey after signing in.</p><Link to="/sign-in">Continue to sign in</Link></div>}</Frame>}
